export enum ChannelPaymentEnum {
    CREDIT_CARD = 'CREDIT_CARD',
    BILL_PAYMENT = 'BILL_PAYMENT', 
    PROMTPAY = 'PROMTPAY',
    COUNTER_SERVICE = 'COUNTER_SERVICE', 
    COUNTER_PAYMENT = 'COUNTER_PAYMENT',  
}